apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    env: "{{ .Values.env }}"
    suite: "{{ .Values.suite }}"
    cluster: "{{ .Values.cluster }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.name }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80